apiVersion: v1
data:
  alert_templates: |
    null
  alertmanager.yml: |
    global:
      smtp_auth_password: Saihaton1
      smtp_auth_username: a.abbas@doitalltech.co.nz
      smtp_from: a.abbas@doitalltech.co.nz
      smtp_smarthost: mail.doitalltech.co.nz:587
    receivers:
    - email_configs:
      - to: support@emergingtechnologypartners.atlassian.net
      name: mails
    route:
      group_by:
      - node
      - cluster
      - service
      group_interval: 5m
      group_wait: 30s
      receiver: mails
      repeat_interval: 3h
      routes:
      - match_re:
          service: ^(mail_serv)$
        receiver: mails
        routes: null
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
    chart: prometheus-7.0.0
    component: alertmanager
    heritage: Tiller
  name: alertmanager