apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: prometheus
  selfLink: /api/v1/namespaces/monitoring/services/prometheus
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: NodePort
status:
  loadBalancer: {}
