
#working main configmap
apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    rule_files:
      - "/etc/prometheus-rules/*.rules"
    scrape_configs:
      - job_name: kubernetes-nodes
        kubernetes_sd_configs:
          - role: node
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - target_label: __scheme__
            replacement: https
          - source_labels:
              - __meta_kubernetes_node_label_kubernetes_io_hostname
            target_label: instance
      - job_name: 'ucp'
        tls_config:
          ca_file: /bundle/ca.pem
          cert_file: /bundle/cert.pem
          key_file: /bundle/key.pem
          server_name: proxy.local
        scheme: https
        file_sd_configs:
        - files:
          - /inventory/inventory.json
      - job_name: 'federate'
        scrape_interval: 15s

        honor_labels: true
        metrics_path: '/federate'

        params:
          'match[]':
            - '{job="ucp"}'

        static_configs:
          - targets:
            - 192.168.1.118:35500
            - 192.168.1.117:35500
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-configmap
  selfLink: /api/v1/namespaces/monitoring/configmaps/prometheus-configmap

