apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    type: local
  name: prom-host
  selfLink: /api/v1/persistentvolumes/prom-host
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: prom-host-claim
    namespace: monitoring
    resourceVersion: "1554315"
    uid: a988fc82-e671-11e8-8d53-0242ac110007
  hostPath:
    path: /root/prom/promethus
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
status: {}